language: java
install:
  - chmod +x gradlew
  - sed -i 's:^[ \t]*build_number[ \t]*=\([ \t]*.*\)$:build_number=\1-SNAPSHOT:' gradle.properties
  - ./gradlew assemble
script:
  - ./gradlew build -Pbranch=$TRAVIS_BRANCH
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
    - gradle
jdk:
  - openjdk8
after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./gradlew publish artifactoryPublish -Pbranch=$TRAVIS_BRANCH -PmavenPassword=$REPO_PWD -PbintrayUser=$BINTRAY_USER -PbintrayApiKey=$BINTRAY_KEY; fi